version: 0.2

env:
  variables:
    ENV: "dev"

phases:
  post_build:
    commands:
      - echo invalidating cache
      - aws cloudfront create-invalidation --distribution-id E280A8KDDMVA81 --paths '/*'
